version: '3'

services: 
    # mongo:
    #     image: mongo
    #     container_name: mongo-service
    #     ports: 
    #         - 27017:27017
    #     expose: 
    #         - 27017
    
    back:
        container_name: "rubros-service"
        restart: always
        environment: 
            - COLLECTION_MONGO=arbol_rubros
            - DB_MONGO=plan_cuentas
            - USER_MONGO=edwar
            - PASS_MONGO=diaz
            - HOST_MONGO=192.168.0.7
            - PORT_MONGO=27019
        build: .
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/src/app
        # depends_on: 
        #     - mongo
        # links: 
        #     - mongo