version: '3'

services:
    mongo:
        image: mongo
        env_file: .develop.env
        ports:
            - '27017:27017'

    back:
        # restart: always
        env_file: .develop.env
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        depends_on:
            - mongo

    psql-db:
        image: postgres:12.1-alpine
        ports:
        - ${POSTGRES_PORT_EXTERNAL}:5432
        environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASS}
        - POSTGRES_DB=${DB_NAME}
        volumes:
        - psql-db-data:/var/lib/postgresql/data
        networks:
        - ws-network

volumes:
    psql-db-data:

networks:
    ws-network:
