version: '3'

services: 
    # mongo:
    #     image: mongo
    #     container_name: mongo-service
    #     ports: 
    #         - 27017:27017
    #     expose: 
    #         - 27017
    
    back:
        container_name: "rubros-service"
        restart: always
        environment: 
            - ESQUEMA_MONGO=arbolitos
            - CONECCION_MONGO=192.168.0.7:27018/prueba
        build: .
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/src/app
        # depends_on: 
        #     - mongo
        # links: 
        #     - mongo